#include "INMP441.h"

static i2s_chan_handle_t                rx_chan;        // I2S rx channel handler

void run_module_1(void)
{
    printf("module 1 is running\n");
}

void call_to_module_1(void)
{
    printf("call to module 1\n");
}
#ifdef I2S_STD
void inmp441_i2s_init_std(void)
{
    /* Setp 1: Determine the I2S channel configuration and allocate two channels one by one
     * The default configuration can be generated by the helper macro,
     * it only requires the I2S controller id and I2S role
     * The tx and rx channels here are registered on different I2S controller,
     * Except ESP32 and ESP32-S2, others allow to register two separate tx & rx channels on a same controller */
    // i2s_chan_config_t tx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    // ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));
    i2s_chan_config_t rx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_0, I2S_ROLE_MASTER);
    // i2s_chan_config_t rx_chan_cfg = {
    //     .id = I2S_NUM_0,
    //     .role = I2S_ROLE_MASTER,
    //     .dma_desc_num = 2,
    //     .dma_frame_num = 32,
    //     .auto_clear_after_cb = false,
    //     .auto_clear_before_cb = false,
    //     .intr_priority = 0
    // };

    ESP_ERROR_CHECK(i2s_new_channel(&rx_chan_cfg, NULL, &rx_chan));

    /* Step 2: Setting the configurations of standard mode and initialize each channels one by one
     * The slot configuration and clock configuration can be generated by the macros
     * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
     * They can help to specify the slot and clock configurations for initialization or re-configuring */

    i2s_std_config_t rx_std_cfg = {
        .clk_cfg  = I2S_STD_CLK_DEFAULT_CONFIG(16000), //44100
        // .slot_cfg = I2S_STD_MSB_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_STD_SLOT_LEFT),
        .slot_cfg = {
            .data_bit_width = I2S_DATA_BIT_WIDTH_16BIT,
            .slot_bit_width = I2S_SLOT_BIT_WIDTH_AUTO,
            .slot_mode = I2S_STD_SLOT_LEFT,
            .slot_mask = I2S_STD_SLOT_LEFT,
            .ws_width = I2S_DATA_BIT_WIDTH_16BIT,
            .ws_pol = false,
            .bit_shift = true,
            .left_align = true,
            .big_endian = false, 
            .bit_order_lsb = false 
        },
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,    // some codecs may require mclk signal, this example doesn't need it
            .bclk = PIN_BCLK,
            .ws   = PIN_WS,
            .dout = PIN_DOUT,
            .din  = PIN_DIN,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv   = false,
            },
        },
    };

    /* Default is only receiving left slot in mono mode,
     * update to right here to show how to change the default configuration */
    // rx_std_cfg.slot_cfg.slot_mask = I2S_STD_SLOT_RIGHT;
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(rx_chan, &rx_std_cfg));

    /* Enable the RX channel */
    ESP_ERROR_CHECK(i2s_channel_enable(rx_chan));
}
void inmp441_i2s_init_pdm(void)
{

    i2s_chan_config_t rx_chan_cfg = {
        .id = I2S_NUM_0,
        .role = I2S_ROLE_MASTER,
        .dma_desc_num = DMA_CNT,
        .dma_frame_num = INMP441_SAMPLE_BUFF_SIZE,
        .auto_clear_after_cb = false,
        .auto_clear_before_cb = false,
        .intr_priority = 0
    };

    ESP_ERROR_CHECK(i2s_new_channel(&rx_chan_cfg, NULL, &rx_chan));

    i2s_pdm_rx_config_t pdm_rx_cfg = {
        .clk_cfg = I2S_PDM_RX_CLK_DEFAULT_CONFIG(44100),
        /* The default mono slot is the left slot (whose 'select pin' of the PDM microphone is pulled down) */
        .slot_cfg = I2S_PDM_RX_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_MONO),
        .gpio_cfg = {
            .clk = PIN_BCLK,
            .din = PIN_DIN,
            .invert_flags = {
                .clk_inv = false,
            },
        },
    };
    ESP_ERROR_CHECK(i2s_channel_init_pdm_rx_mode(rx_chan, &pdm_rx_cfg));
    ESP_ERROR_CHECK(i2s_channel_enable(rx_chan));
}

size_t inmp441_read_raw_data(int16_t * desc_buf)
{
    size_t bytesIn = 0;
    i2s_channel_read(rx_chan, desc_buf, INMP441_SAMPLE_BUFF_SIZE, &bytesIn, 0xffffffffUL);
    return bytesIn;
}

esp_err_t inmp441_read_raw_data_pdm(int16_t * desc_buf)
{
    esp_err_t result = i2s_channel_read(rx_chan, desc_buf, INMP441_SAMPLE_BUFF_SIZE, NULL, 0xffffffffUL);
    return result;
}

#else
void inmp441_i2s_init_lagacy(void)
{
    const i2s_config_t i2s_config = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX),
        .sample_rate = 44100,
        // .sample_rate = 16000,
        .bits_per_sample = (i2s_bits_per_sample_t)(16),
        .channel_format = I2S_CHANNEL_FMT_ONLY_LEFT,
        .communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_STAND_I2S),
        .intr_alloc_flags = 0,
        .dma_buf_count = DMA_CNT,
        .dma_buf_len = EXAMPLE_BUFF_SIZE,
        .use_apll = false
    };

    i2s_driver_install(I2S_PORT, &i2s_config, 0, NULL);

    // Set I2S pin configuration
    const i2s_pin_config_t pin_config = {
        .bck_io_num = PIN_BCLK,
        .ws_io_num = PIN_WS,
        .data_out_num = -1,
        .data_in_num = PIN_DIN
    };

  i2s_set_pin(I2S_PORT, &pin_config);
  i2s_start(I2S_PORT);
}


esp_err_t inmp441_read_raw_data_legacy(int16_t * desc_buf)
{
    size_t bytesIn = 0;
    esp_err_t result = i2s_read(I2S_PORT, &desc_buf, EXAMPLE_BUFF_SIZE, &bytesIn, portMAX_DELAY);
    return result;
}
#endif
